### ISSUE TITLE
problems in android location get

### ISSUE THREAD

**Issue by arun-lokas** [flutter-devs/geo_location_finder#2]
I have tried it works. Only if it already we have a enable GPS location. otherwise, it's not getting the locations.

kindly help us. I'm in the middle of developing
my email id is arun@lokas.info

**Comment by DedSecTeam17** [comment]
Same problem. give me an exception 


`E/flutter ( 8757): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 8757): MissingPluginException(No implementation found for method getLocation on channel github.com/geo_location_finder)
E/flutter ( 8757): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 8757): <asynchronous suspension>
E/flutter ( 8757): #1      GeoLocation.getLocation (package:geo_location_finder/geo_location_finder.dart:34:33)`
